// Ready-made sample designs. Each is a complete design object; loading one
// replaces the current design (after confirmation).

export const PRESETS = [
  {
    name: 'Sedan (TL8)',
    tl: 8, chassis: 'wheeled', maxLWt: 4500, quality: 'standard',
    streamlining: 'streamlined', cab: 'enclosed', wheels: 4,
    lengthAuto: true, lengthYds: 5,
    engine: 'gasoline', power: 180, fuelLbs: 90,
    armor: { material: 'hardSteel', front: 4, sides: 3, rear: 3, top: 3, under: 3 },
    crew: 1, passengers: 3, cargoLbs: 300,
    accessories: ['headlights', 'radio', 'navigation', 'climate'],
    weapons: [],
  },
  {
    name: 'Sport Motorcycle (TL8)',
    tl: 8, chassis: 'motorcycle', maxLWt: 1400, quality: 'standard',
    streamlining: 'streamlined', cab: 'exposed', wheels: 2,
    lengthAuto: true, lengthYds: 2.5,
    engine: 'gasoline', power: 60, fuelLbs: 30,
    armor: { material: 'hardSteel', front: 0, sides: 0, rear: 0, top: 0, under: 0 },
    crew: 1, passengers: 1, cargoLbs: 20,
    accessories: ['headlights'],
    weapons: [],
  },
  {
    name: 'Pickup Truck (TL8)',
    tl: 8, chassis: 'wheeled', maxLWt: 8500, quality: 'heavy',
    streamlining: 'standard', cab: 'enclosed', wheels: 4,
    lengthAuto: true, lengthYds: 6,
    engine: 'diesel', power: 250, fuelLbs: 180,
    armor: { material: 'hardSteel', front: 4, sides: 3, rear: 3, top: 3, under: 3 },
    crew: 1, passengers: 2, cargoLbs: 2000,
    accessories: ['headlights', 'radio', 'navigation', 'climate', 'offroad', 'winch'],
    weapons: [],
  },
  {
    name: 'Main Battle Tank (TL8)',
    tl: 8, chassis: 'tracked', maxLWt: 140000, quality: 'standard',
    streamlining: 'boxy', cab: 'enclosed',
    lengthAuto: true, lengthYds: 9,
    engine: 'gasTurbine', power: 1500, fuelLbs: 3500,
    armor: { material: 'composite', front: 400, sides: 150, rear: 60, top: 60, under: 40 },
    crew: 4, passengers: 0, cargoLbs: 400,
    accessories: ['headlights', 'radio', 'navigation', 'sealedCab', 'climate', 'smoke', 'fireSuppression'],
    weapons: [
      { name: '120mm tank gun', weight: 4200, cost: 500000, dmg: '6d×15 pi++', mount: 'turret', qty: 1, minTL: 7 },
      { name: '7.62mm machine gun', weight: 30, cost: 6000, dmg: '7d pi', mount: 'open', qty: 1, minTL: 6 },
    ],
  },
  {
    name: 'Patrol Boat (TL8)',
    tl: 8, chassis: 'planingBoat', maxLWt: 30000, quality: 'standard',
    streamlining: 'standard', cab: 'enclosed',
    lengthAuto: true, lengthYds: 13,
    engine: 'diesel', power: 1200, fuelLbs: 4000,
    armor: { material: 'aluminum', front: 3, sides: 3, rear: 3, top: 3, under: 3 },
    crew: 4, passengers: 2, cargoLbs: 2000,
    accessories: ['radio', 'navigation', 'searchlight', 'autopilot'],
    weapons: [
      { name: '12.7mm heavy MG', weight: 130, cost: 14000, dmg: '13d+1 pi+', mount: 'open', qty: 2, minTL: 6 },
    ],
  },
  {
    name: 'Light Airplane (TL7)',
    tl: 7, chassis: 'airplane', maxLWt: 3000, quality: 'standard',
    streamlining: 'streamlined', cab: 'enclosed', wheels: 3,
    lengthAuto: true, lengthYds: 10,
    engine: 'gasoline', power: 180, fuelLbs: 200,
    armor: { material: 'aluminum', front: 0, sides: 0, rear: 0, top: 0, under: 0 },
    crew: 1, passengers: 3, cargoLbs: 60,
    accessories: ['radio'],
    weapons: [],
  },
  {
    name: 'Utility Helicopter (TL8)',
    tl: 8, chassis: 'helicopter', maxLWt: 6000, quality: 'standard',
    streamlining: 'standard', cab: 'enclosed',
    lengthAuto: true, lengthYds: 11,
    engine: 'gasTurbine', power: 800, fuelLbs: 800,
    armor: { material: 'aluminum', front: 2, sides: 2, rear: 2, top: 2, under: 2 },
    crew: 2, passengers: 4, cargoLbs: 200,
    accessories: ['radio', 'navigation', 'autopilot', 'searchlight'],
    weapons: [],
  },
  {
    name: 'Steam Launch (TL5)',
    tl: 5, chassis: 'boat', maxLWt: 8000, quality: 'standard',
    streamlining: 'standard', cab: 'open',
    lengthAuto: true, lengthYds: 9,
    engine: 'steam', power: 20, fuelLbs: 800,
    armor: { material: 'wood', front: 1, sides: 1, rear: 1, top: 0, under: 1 },
    crew: 1, passengers: 6, cargoLbs: 500,
    accessories: [],
    weapons: [],
  },
  {
    name: 'Electric Runabout (TL9)',
    tl: 9, chassis: 'wheeled', maxLWt: 4800, quality: 'standard',
    streamlining: 'streamlined', cab: 'enclosed', wheels: 4,
    lengthAuto: true, lengthYds: 5,
    engine: 'electric', power: 250, fuelLbs: 900,
    armor: { material: 'composite', front: 5, sides: 4, rear: 4, top: 4, under: 4 },
    crew: 1, passengers: 3, cargoLbs: 350,
    accessories: ['headlights', 'radio', 'navigation', 'climate', 'selfDriving'],
    weapons: [],
  },
];
