// ---------------------------------------------------------------------------
// Explain-mode content for the Vehicles 2e designer: what every choice
// represents in a real vehicle.
// ---------------------------------------------------------------------------

export const SECTION_HELP = {
  'Basics': 'Who built this vehicle and how well. These choices set the technology available everywhere else.',
  'Hull & Features': 'The overall shape and nature of the hull: does it float, dive, cut through air or water, protect its crew from the environment?',
  'Structure': 'The skeleton and skin: the frame and girders everything else bolts to. Stronger frames survive more damage but weigh and cost more.',
  'Armor': 'Protective plating over the hull. DR (Damage Resistance) is how many points of damage the armor stops from every hit.',
  'Subassemblies': 'The parts that stick out of the body: what it rolls/walks/flies on, plus turrets, superstructures, mounts and arms that house equipment.',
  'Components': 'Everything installed inside: engines, drivetrains, fuel tanks, seats, sensors, weapons. Each takes up weight, space and money, and may make or use power.',
  'Crew, Payload & Fuel': 'Who and what the vehicle carries. People and cargo add weight; fuel adds weight and grants endurance.',
  'Options': 'Drivetrain and control upgrades that improve handling, braking or stability for extra cost.',
};

export const FIELD_HELP = {
  'f-name': 'Whatever you want to call the design — it appears on the stat sheet and exports.',
  'f-tl': 'Tech Level: the engineering era. TL5 is the steam age (~1850), TL6 WWII, TL7 the Cold War, TL8 near-future, TL9+ science fiction. Higher TL means lighter structures, better armor materials, and more advanced components.',
  'f-controls': 'How the driver’s inputs reach the machinery.',
  'f-streamlining': 'How aerodynamically the hull is shaped. Better streamlining cuts air drag (faster over ~50 mph, much faster in flight) but costs more to build and wastes internal space on fairings.',
  'f-length4': 'The vehicle’s longest dimension, used only to compute the 4e Size Modifier. Leave 0 to estimate it from total volume.',

  'f-flotation': 'A watertight, boat-shaped lower hull. Required for anything meant to float — the hull must displace more water weight than the vehicle weighs.',
  'f-submersible': 'A double hull with ballast tanks and diving planes, like a submarine. Includes sealing and waterproofing, but doubles structure weight and cost.',
  'f-sealed': 'Airtight construction with overpressure protection — needed for NBC defense, high altitude, or driving along the bottom. Requires at least DR 1 everywhere.',
  'f-catamaran': 'Two (or three) parallel hulls, like a catamaran ferry. Much more stable in waves, at the cost of wasted internal volume.',
  'f-liftingbody': 'The fuselage itself is shaped to generate lift, like the Space Shuttle — smaller wings needed, but requires Very Good or better streamlining.',
  'f-responsive': 'A TL8+ structure that subtly reshapes itself in motion — think adaptive skin — improving maneuverability and stall behavior.',
  'f-space': 'Also report space performance (acceleration in Gs) from the vehicle’s rocket/thruster thrust.',
  'f-hydrolines': 'The hull’s underwater shape.',
  'f-frame': 'How massive the load-bearing skeleton is.',
  'f-material': 'What the structure is built from, quality-wise.',
  'f-special': 'Exotic structure types.',

  'f-armortype': 'The armor material and its manufacturing quality. Better materials stop the same damage at a fraction of the weight — for a price.',
  'f-armormode': 'Overall armor wraps the same DR around everything (simple, like a civilian car). Facing armor lets you pile protection where hits come from — like a tank with a thick glacis and thin roof.',
  'f-dr': 'Damage Resistance everywhere: each point stops one point of damage from every hit, over the entire vehicle including subassemblies.',
  'f-otherdr': 'DR applied to everything that isn’t the body, a turret or a superstructure — wheels, tracks, wings, rotors and so on. Rotors need at least DR 5.',

  's-wheels': 'Rolls on wheels — the default for ground vehicles. Fast and cheap, but the worst choice off-road.',
  's-wheeltype': 'What kind of wheels.',
  's-wheelcount': 'More wheels spread the load (better stability for big vehicles) and give more hit locations to shoot out.',
  's-wheelretract': 'Wheels fold into the body like aircraft landing gear — less drag in flight, but they take up internal space.',
  's-tracks': 'Caterpillar tracks, like a tank or bulldozer: excellent off-road grip and braking, huge ground contact, but bulky (60% of body volume) and slower.',
  's-halftracks': 'Front wheels for steering plus rear tracks for traction — the WWII compromise between trucks and tanks.',
  's-skids': 'Runners or skis: sleds, helicopters’ landing skids, snow vehicles. Poor acceleration and braking on most surfaces.',
  's-legs': 'Walking legs, like a mech. Superb off-road (full speed anywhere) and agile at low speed, but mechanically complex and less stable.',
  's-legcount': 'Two legs are agile but tippy; four or more are steadier and faster in this system.',
  's-wings': 'Fixed wings that generate lift when moving forward. The vehicle can fly once it exceeds its stall speed.',
  's-wingtype': 'The wing planform.',
  's-wingfrac': 'How big each wing is, as a fraction of body volume. Bigger wings = lower stall speed and better agility; smaller wings = less drag and higher top speed.',
  's-rotors': 'Helicopter rotors: lift without forward speed, so the vehicle can hover — but top speed is capped (150 mph at TL6, 300 at TL7+).',
  's-masts': 'Masts and rigging for sails. Limits streamlining to Fair.',
  's-mastheight': 'Height of the tallest mast. Taller masts demand a larger hull to stay upright.',
  's-gasbag': 'A lighter-than-air envelope, like a blimp’s. Enormous but nearly weightless; provides lift via lifting gas.',
  's-gasbagcf': 'Volume of the gas envelope in cubic feet. Hydrogen lifts 1 lb per ~15 cf, helium per ~16 cf.',

  'c-name': 'What this part is — engine, drivetrain, seat, gun, sensor…',
  'c-weight': 'How much the component weighs. Everything you install makes the vehicle heavier and slower.',
  'c-cost': 'Purchase price of the component, added to the vehicle’s total.',
  'c-volume': 'Internal space it occupies, in cubic feet. The body grows to fit its contents — bulky parts mean a bigger, heavier vehicle.',
  'c-gph': 'Fuel burned per hour of operation, in gallons. Determines endurance from the fuel supply.',
  'c-kwin': 'Electrical/mechanical power this component consumes while running. Your power plants must supply at least this much in total.',
  'c-kwout': 'Power this component generates (engines, generators, batteries discharging).',
  'c-groundkw': 'Motive power delivered to wheels/tracks/legs — the number that sets ground speed. A drivetrain converts engine kW into this.',
  'c-aqua': 'Pounds of thrust pushing the vehicle through water (propellers, hydrojets, paddle wheels).',
  'c-air': 'Pounds of thrust pushing the vehicle through air (propellers, jets, rockets). Also contributes a quarter of its value to ground speed for wheeled vehicles.',
  'c-lift': 'Pounds of static lift holding the vehicle up without forward motion: helicopter rotors, lifting gas, lift fans. Lift ≥ loaded weight means it can hover.',
  'c-contragrav': 'Antigravity lift (TL12+ superscience). Cancels weight for ground pressure, water drag and draft as well as flight.',
  'c-airbreathing': 'This component needs outside air (combustion engines, jets) — it shuts down underwater.',
  'c-location': 'Where the component is installed. Parts in turrets/arms move with them and are hit separately; body parts are behind body armor.',

  'f-crew': 'People needed to operate the vehicle: drivers, gunners, engineers. Each weighs 200 lbs with gear, and needs a crew station component.',
  'f-passengers': 'People carried but not working. Each weighs 200 lbs with gear, and needs a seat component.',
  'f-exposed': 'How many occupants ride in the open (motorcycle saddle, jeep seats, open cockpit). Each adds air drag in flight and hover.',
  'f-cargocf': 'Dedicated cargo space in cubic feet. Each cf of cargo space is assumed to carry 20 lbs of payload.',
  'f-emptycf': 'Deliberate unused volume. Sounds wasteful, but it’s how you enlarge a hull for buoyancy, future upgrades, or to fit oversized turrets.',
  'f-fueltype': 'What the tanks hold. Determines weight per gallon and fire risk — gasoline burns easily, diesel much less so.',
  'f-fuelgal': 'Gallons carried. More fuel means longer endurance but a heavier vehicle. Remember to add a fuel tank component to hold it.',
  'f-hpcount': 'External weapon pylons, like a combat aircraft’s. Each loaded hardpoint adds drag.',
  'f-hpload': 'Maximum total weight of bombs/missiles/pods on the hardpoints. Performance is computed with and without this load.',

  'o-suspension': 'Better springs and dampers: +2 to the speed factor for wheels (+1 for others), better handling (+0.25 gMR) and stability (+1 gSR).',
  'o-brakes': 'Bigger, better brakes: +5 mph/s deceleration for wheeled vehicles.',
  'o-aws': 'All four (or more) wheels steer, tightening the turning circle: +0.25 gMR.',
  'o-awd': 'Power to every wheel. Doesn’t change top speed, but dramatically improves off-road capability (category III instead of IV).',
  'o-smartwheels': 'TL8+ computer-managed wheels: +0.25 gMR and +5 mph/s braking.',
  'o-rollstab': 'Gyroscopic fins or active ballast on watercraft: +1 wSR against rolling in waves.',
};

export const OPTION_HELP = {
  'f-controls': {
    mechanical: 'Selected: cables, rods and hydraulics — a 1950s steering wheel and pedals. No bonuses, nothing to short out.',
    electronic: 'Selected: fly-by-wire servos (TL6+): control inputs travel as signals, improving maneuver and stability ratings.',
    computerized: 'Selected: a computer interprets the pilot (TL7+): best maneuver/stability bonuses, and enables high-agility tricks.',
  },
  'f-streamlining': {
    none: 'Selected: a box on wheels — no aerodynamic shaping at all.',
    fair: 'Selected: gently rounded, like a sports car or light aircraft.',
    good: 'Selected: consciously slippery — race cars, fast propeller planes.',
    veryGood: 'Selected: subsonic jet shaping; needed for a lifting body.',
    superior: 'Selected: slow supersonic jet shaping.',
    excellent: 'Selected: fast supersonic jet shaping.',
    radical: 'Selected: missile/hypersonic shaping — maximum speed, minimum practicality.',
  },
  'f-hydrolines': {
    none: 'Selected: not shaped for water at all — a floating box has enormous water drag.',
    mediocre: 'Selected: a tubby boat hull (length ~3-5× beam): river boats, bulk freighters.',
    average: 'Selected: a sleeker hull (~5-7:1): powerboats, clippers, liners.',
    fine: 'Selected: a knife-like hull (8:1+): warships, racing shells.',
    veryFine: 'Selected: fine lines with an optimized shape — the fastest surface hull.',
    submarine: 'Selected: a teardrop optimized for travel underwater (TL7+), at the cost of surface speed.',
  },
  'f-frame': {
    superLight: 'Selected: gossamer construction — balloons, early aircraft. A tenth the weight, a tenth the durability.',
    extraLight: 'Selected: wagons, early biplanes, simple boats. Fragile but cheap and light.',
    light: 'Selected: cars, light planes, speedboats. The civilian standard.',
    medium: 'Selected: transport aircraft, wooden warships — a solid working frame.',
    heavy: 'Selected: trucks, steamships, armored vehicles. Takes double punishment.',
    extraHeavy: 'Selected: locomotives, battleships, jet fighters. Massive — 4× the hit points, 5× the cost.',
  },
  'f-material': {
    veryCheap: 'Selected: scrap and green timber: half price, but twice the weight.',
    cheap: 'Selected: budget-grade materials: 50% heavier, half the cost.',
    standard: 'Selected: normal commercial construction.',
    expensive: 'Selected: aircraft-grade alloys: 25% lighter for double cost.',
    veryExpensive: 'Selected: exotic alloys and honeycombs (TL5+): half weight, 5× cost.',
    advanced: 'Selected: composites and advanced ceramics (TL6+): 62.5% lighter, 10× cost.',
  },
  'f-special': {
    none: 'Selected: a conventional structure.',
    responsive: 'Selected: shape-adjusting structure (TL8+), pairs with the Responsive feature.',
    robotic: 'Selected: built to be run by a robot brain (TL7+) — internal data highways everywhere.',
    biomechanical: 'Selected: part organic (TL9+): it heals 1 HP/day, but can feel pain and get sick.',
    livingMetal: 'Selected: self-repairing nanotech metal (TL13): regenerates 1 HP per hour.',
  },
  's-wheeltype': {
    standard: 'Selected: ordinary road wheels and tires.',
    small: 'Selected: compact wheels (carts, small robots): less internal space used, but -1 stability and poor obstacle handling.',
    heavy: 'Selected: big load-bearing wheels for heavy trucks.',
    offroad: 'Selected: fat, deep-tread tires: double contact area for soft ground.',
    railway: 'Selected: flanged steel wheels: double speed on rails, useless off them.',
  },
  's-wingtype': {
    standard: 'Selected: conventional wings.',
    stol: 'Selected: big high-lift wings: much lower stall speed and shorter takeoffs, more drag.',
    highAgility: 'Selected: fighter-style wings: better maneuverability.',
    biplane: 'Selected: stacked double wings: lots of lift at low speed, lots of drag, -1 aerial stability.',
    triplane: 'Selected: three stacked wings: even more so.',
    stub: 'Selected: vestigial winglets that provide no real lift — mounting points for weapons, mostly.',
  },
  'f-fueltype': {
    gasoline: 'Selected: 6 lbs/gallon, ignites easily (fire 11) — the classic “f” on your HT.',
    diesel: 'Selected: 6 lbs/gallon, hard to ignite (fire 9) — no flammability penalty.',
    avgas: 'Selected: high-octane aviation gasoline, 6.5 lbs/gallon, very flammable.',
    jetFuel: 'Selected: kerosene for turbines, 6.5 lbs/gallon, flammable.',
    alcohol: 'Selected: 5.8 lbs/gallon, burns with an almost invisible flame.',
    propane: 'Selected: bottled gas, 4.2 lbs/gallon, quite flammable.',
    hydrogen: 'Selected: featherweight (0.58 lbs/gallon) but explosive — expect an “x”.',
    rocketFuel: 'Selected: 10 lbs/gallon of barely-contained energy.',
    water: 'Selected: reaction mass or boiler feed — inert.',
    metalLox: 'Selected: metal-slurry/LOX exotic propellant, 12 lbs/gallon.',
    lox: 'Selected: liquid oxygen oxidizer, 9.6 lbs/gallon; makes everything else burn better.',
  },
};

// Tooltips for the computed stats on the sheet (keyed by row label).
export const STAT_HELP = {
  'Body volume': 'Internal space of the main hull: everything installed in the body, plus slope/streamlining/hull-form overhead. Bigger bodies mean more surface to build and armor.',
  'Total volume / Size Modifier': 'All volumes combined. SM is the to-hit size bonus: +3 means car-sized (easier to hit than a person by 3).',
  'Surface area (total / structural)': 'The vehicle’s skin in square feet. Structural area (excluding masts, open mounts, gasbags) is what structure weight, armor weight and sealing costs are computed from.',
  'Structure': 'Weight and cost of the frame and skin, from surface area × TL × frame strength × materials.',
  'Armor weight & cost': 'Total plating: area covered × DR × material weight-per-DR.',
  'Coverage': 'PD (Passive Defense) is the 3e dodge-ish bonus from armor shape; DR stops damage points from each hit.',
  'Empty weight': 'The vehicle with no people, cargo, fuel or ammo aboard.',
  'Payload (people + cargo)': '200 lbs per person plus 20 lbs per cubic foot of cargo space.',
  'Fuel': 'Weight of the full fuel load.',
  'Loaded weight': 'Everything aboard: the weight used for all performance math.',
  'With hardpoints loaded': 'Loaded weight plus maximum external stores.',
  'Flotation': 'The maximum weight the hull can displace and still float. If loaded weight exceeds this, it sinks.',
  'Submerged weight': 'Underwater the hull floods or ballasts to neutral: the greater of loaded weight or 62.5 lbs × volume.',
  'Power': 'Total kW your components draw vs what your power plants make. Running short means things switch off.',
  'Fuel use': 'Combined burn rate of all engines, and how long a full tank lasts.',
  'Health (HT)': 'The vehicle’s “constitution” for breakdown and survival rolls, from body hit points vs loaded weight.',
  'Price': 'Total cost of structure, armor and every component (fuel and ammo not included).',
  'Top speed': 'Maximum sustained speed in this environment.',
  'gAccel / gDecel': 'How fast it speeds up / safely brakes, in mph per second.',
  'gMR / gSR': 'Maneuver Rating: the Gs it can pull turning (higher = nimbler). Stability Rating: resistance to skids and rollovers (higher = steadier).',
  'Ground pressure': 'Weight divided by ground-contact area. Low pressure floats over mud and snow; high pressure digs in.',
  'Off-road speed': 'Fraction of top speed usable off paved surfaces, from ground pressure and drive type.',
  'wAccel / wDecel': 'Acceleration and safe deceleration on water, mph per second (powered figure in parentheses).',
  'wMR / wSR': 'Water maneuver (Gs in a turn) and stability (resistance to rolling in waves).',
  'Draft': 'How deep the hull sits — the minimum water depth it can float in without grounding.',
  'uAccel': 'Underwater acceleration in mph per second.',
  'Draft / Crush depth': 'Submerged draft, and the depth in yards beyond which the pressure hull fails.',
  'Stall speed': 'Minimum airspeed to stay aloft. 0 means it can hover and take off vertically.',
  'aAccel / aDecel': 'Airborne acceleration and safe deceleration, mph per second.',
  'aMR / aSR': 'Aerial maneuver rating (max Gs in a turn) and stability (resistance to stalls and spins).',
  'Takeoff run': 'Runway needed to reach stall speed at ground acceleration.',
  'With stores': 'The same aerial figures with hardpoints loaded.',
  'sAccel': 'Space acceleration from thrust vs mass, in Gs and mph/s.',
  'sMR': 'Space maneuver rating — equal to acceleration.',
  'Flight': 'Whether it can get airborne on its own: stall speed must be 0 or reachable on the ground/water.',
};
