// Sample VE2 designs. Component numbers follow the book's component rules
// (engine/drivetrain weights per kW, hydrojet thrust 12 lbs/kW, helicopter
// lift 10 lbs/kW & thrust 1.6 lbs/kW, etc.).

export const VE2_PRESETS = [
  {
    name: 'TL6 Jeep',
    tl: 6, controls: 'mechanical', streamlining: 'none',
    features: { flotationHull: false, submersibleHull: false, hydroLines: 'none', catamaran: false, trimaran: false, sealed: false, waterproofed: false, liftingBody: false, responsive: false },
    structure: { frame: 'light', material: 'cheap', special: 'none' },
    armor: { type: 'metalExpensive', mode: 'overall', dr: 3, faces: null, otherDr: 0 },
    subassemblies: {
      wheels: { present: true, type: 'offroad', count: 4, retractable: false },
      tracks: { present: false }, halftracks: { present: false }, skids: { present: false },
      legs: { present: false, count: 2 },
      wings: { present: false, type: 'standard', volumeFrac: 0.1 },
      rotors: { present: false, tl: 7 },
      turrets: [], superstructures: [],
      masts: { present: false, heightFt: 30 },
      gasbag: { present: false, cf: 0 },
    },
    components: [
      { name: 'gasoline engine, 40 kW', weight: 270, cost: 540, volume: 10.8, kwOut: 40, fuelGph: 1.8, airBreathing: true, location: 'body' },
      { name: 'wheeled drivetrain, 40 kW', weight: 120, cost: 480, volume: 4.8, kwIn: 40, groundKw: 40, location: 'body' },
      { name: 'fuel tank, 10 gal', weight: 5, cost: 20, volume: 1.5, location: 'body' },
      { name: 'lead-acid battery', weight: 60, cost: 60, volume: 0.5, location: 'body' },
      { name: 'crew station (driver, exposed)', weight: 50, cost: 250, volume: 15, location: 'body' },
      { name: '3 passenger seats (exposed)', weight: 90, cost: 150, volume: 40, location: 'body' },
      { name: 'tow hitch', weight: 10, cost: 10, volume: 0.1, location: 'body' },
    ],
    crew: 1, passengers: 3, exposedSeats: 4, cargoCf: 20, emptySpaceCf: 0,
    fuel: { type: 'gasoline', gallons: 10 },
    hardpoints: { count: 0, loadLbs: 0 },
    options: { improvedSuspension: false, improvedBrakes: false, allWheelSteering: false, allWheelDrive: true, smartwheels: false, rollStabilizers: false },
  },
  {
    name: 'TL7 Main Battle Tank',
    tl: 7, controls: 'electronic', streamlining: 'none',
    features: { flotationHull: false, submersibleHull: false, hydroLines: 'none', catamaran: false, trimaran: false, sealed: true, waterproofed: false, liftingBody: false, responsive: false },
    structure: { frame: 'extraHeavy', material: 'standard', special: 'none' },
    armor: {
      type: 'compositeStandard', mode: 'facing',
      dr: 0,
      faces: {
        front: { dr: 450, slope: 60 }, back: { dr: 60, slope: 0 },
        left: { dr: 150, slope: 0 }, right: { dr: 150, slope: 0 },
        top: { dr: 50 }, under: { dr: 50 },
      },
      otherDr: 30,
    },
    subassemblies: {
      wheels: { present: false, type: 'standard', count: 4, retractable: false },
      tracks: { present: true }, halftracks: { present: false }, skids: { present: false },
      legs: { present: false, count: 2 },
      wings: { present: false, type: 'standard', volumeFrac: 0.1 },
      rotors: { present: false, tl: 7 },
      turrets: [{ volumeCf: 180, rotation: 'full', slopeDegrees: 60, dr: 250 }],
      superstructures: [],
      masts: { present: false, heightFt: 30 },
      gasbag: { present: false, cf: 0 },
    },
    components: [
      { name: 'diesel engine, 900 kW', weight: 5400, cost: 27000, volume: 108, kwOut: 900, fuelGph: 31.5, airBreathing: true, location: 'body' },
      { name: 'tracked drivetrain, 900 kW', weight: 4500, cost: 18000, volume: 90, kwIn: 900, groundKw: 900, location: 'body' },
      { name: 'fuel tanks, 350 gal', weight: 175, cost: 700, volume: 52, location: 'body' },
      { name: '120mm tank gun', weight: 4400, cost: 250000, volume: 88, location: 'turret0' },
      { name: '40 rounds 120mm ammo', weight: 2200, cost: 40000, volume: 44, location: 'turret0' },
      { name: 'coaxial 7.62mm MG + ammo', weight: 100, cost: 6500, volume: 2, location: 'turret0' },
      { name: '4 crew stations (cramped)', weight: 240, cost: 4000, volume: 120, location: 'body' },
      { name: 'radios, sensors & fire control', weight: 300, cost: 60000, volume: 6, kwIn: 5, location: 'turret0' },
      { name: 'environmental control', weight: 200, cost: 2000, volume: 4, kwIn: 2, location: 'body' },
    ],
    crew: 4, passengers: 0, cargoCf: 10, emptySpaceCf: 0,
    fuel: { type: 'diesel', gallons: 350 },
    hardpoints: { count: 0, loadLbs: 0 },
    options: { improvedSuspension: true, improvedBrakes: false, allWheelSteering: false, allWheelDrive: false, smartwheels: false, rollStabilizers: false },
  },
  {
    name: 'TL7 Speedboat',
    tl: 7, controls: 'mechanical', streamlining: 'fair',
    features: { flotationHull: true, submersibleHull: false, hydroLines: 'mediocre', catamaran: false, trimaran: false, sealed: false, waterproofed: true, liftingBody: false, responsive: false },
    structure: { frame: 'light', material: 'standard', special: 'none' },
    armor: { type: 'metalStandard', mode: 'overall', dr: 2, faces: null, otherDr: 0 },
    subassemblies: {
      wheels: { present: false, type: 'standard', count: 4, retractable: false },
      tracks: { present: false }, halftracks: { present: false }, skids: { present: false },
      legs: { present: false, count: 2 },
      wings: { present: false, type: 'standard', volumeFrac: 0.1 },
      rotors: { present: false, tl: 7 },
      turrets: [], superstructures: [],
      masts: { present: false, heightFt: 30 },
      gasbag: { present: false, cf: 0 },
    },
    components: [
      { name: 'gasoline engine, 200 kW', weight: 1200, cost: 4800, volume: 48, kwOut: 200, fuelGph: 8, airBreathing: true, location: 'body' },
      { name: 'hydrojet, 200 kW', weight: 500, cost: 4000, volume: 10, kwIn: 200, aquaticThrust: 2400, location: 'body' },
      { name: 'fuel tank, 80 gal', weight: 40, cost: 160, volume: 12, location: 'body' },
      { name: 'crew station (open)', weight: 50, cost: 250, volume: 15, location: 'body' },
      { name: '5 passenger seats (open)', weight: 150, cost: 250, volume: 65, location: 'body' },
    ],
    crew: 1, passengers: 5, cargoCf: 15, emptySpaceCf: 60,
    fuel: { type: 'gasoline', gallons: 80 },
    hardpoints: { count: 0, loadLbs: 0 },
    options: { improvedSuspension: false, improvedBrakes: false, allWheelSteering: false, allWheelDrive: false, smartwheels: false, rollStabilizers: false },
  },
  {
    name: 'TL7 Light Helicopter',
    tl: 7, controls: 'electronic', streamlining: 'fair',
    features: { flotationHull: false, submersibleHull: false, hydroLines: 'none', catamaran: false, trimaran: false, sealed: false, waterproofed: false, liftingBody: false, responsive: false },
    structure: { frame: 'light', material: 'expensive', special: 'none' },
    armor: { type: 'metalStandard', mode: 'overall', dr: 5, faces: null, otherDr: 0 },
    subassemblies: {
      wheels: { present: false, type: 'standard', count: 4, retractable: false },
      tracks: { present: false }, halftracks: { present: false },
      skids: { present: true },
      legs: { present: false, count: 2 },
      wings: { present: false, type: 'standard', volumeFrac: 0.1 },
      rotors: { present: true, tl: 7 },
      turrets: [], superstructures: [],
      masts: { present: false, heightFt: 30 },
      gasbag: { present: false, cf: 0 },
    },
    components: [
      { name: 'gas turbine, 850 kW', weight: 1275, cost: 34000, volume: 25.5, kwOut: 850, fuelGph: 46.75, airBreathing: true, location: 'body' },
      // Helicopter drivetrain: lift = 10 lbs/kW, thrust = 1.6 lbs/kW.
      { name: 'helicopter drivetrain, 800 kW', weight: 2400, cost: 32000, volume: 48, kwIn: 800, airThrust: 1280, staticLift: 8000, location: 'body' },
      { name: 'fuel tank, 90 gal', weight: 45, cost: 180, volume: 13.5, location: 'body' },
      { name: '2 crew stations', weight: 100, cost: 500, volume: 30, location: 'body' },
      { name: '4 passenger seats', weight: 120, cost: 200, volume: 52, location: 'body' },
      { name: 'avionics & radios', weight: 100, cost: 20000, volume: 2, kwIn: 2, location: 'body' },
    ],
    crew: 2, passengers: 4, cargoCf: 12, emptySpaceCf: 0,
    fuel: { type: 'jetFuel', gallons: 90 },
    hardpoints: { count: 2, loadLbs: 500 },
    options: { improvedSuspension: false, improvedBrakes: false, allWheelSteering: false, allWheelDrive: false, smartwheels: false, rollStabilizers: false },
  },
];
